steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-app:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/php-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'php-app', '--image=gcr.io/$PROJECT_ID/php-app:$COMMIT_SHA', '--region=us-central1', '--platform=managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/php-app:$COMMIT_SHA'
