steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-app:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/php-app:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'php-app', '--image', 'gcr.io/$PROJECT_ID/php-app:$SHORT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

options:
  logging: GCS_ONLY
logsBucket: gs://php-static-files-459809/build-logs/
