steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-app', '.']
    dir: 'docker'

images:
  - 'gcr.io/$PROJECT_ID/php-app'

options:
  logging: CLOUD_LOGGING_ONLY # This ensures logs go to Cloud Logging
  logs_bucket: gs://valid-kayak-logs/ # Make sure this bucket exists

serviceAccount: 454751535014-compute@developer.gserviceaccount.com  # Your custom service account
