steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-app', '.']
    dir: 'docker'

images:
  - 'gcr.io/$PROJECT_ID/php-app'

options:
  logging: CLOUD_LOGGING_ONLY  # Ensures logs are directed to Cloud Logging
  # No need to define a logs_bucket here

serviceAccount: 454751535014-compute@developer.gserviceaccount.com  # Your custom service account
